### ISSUE TITLE
`Search Commands` expects a non existing `commands.json`file

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam-raycast#2]
I installed the latest version of sunbeam on brew (`1.0.0-rc.19`) but I am getting an error on Raycast when using `Search Commands`: 

```
Error: ENOENT: no such file or directory, open '/Users/my_user/Library/Application Support/Sunbeam/commands.json'
```

I think that at first, my folder `/Users/my_user/Library/Application Support/Sunbeam` didn't contain anything but now it contains the following (`gh` is a custome one):

```
.
└── extensions
    ├── bw
    │   ├── manifest.json
    │   └── src
    │       └── sunbeam-extension
    ├── devdocs
    │   ├── manifest.json
    │   └── src
    │       └── sunbeam-extension
    ├── files
    │   ├── manifest.json
    │   └── src
    │       └── sunbeam-extension
    ├── gh
    │   └── manifest.json
    ├── github
    │   ├── manifest.json
    │   └── src
    │       └── sunbeam-extension
    └── vsc
        ├── manifest.json
        └── sunbeam-extension
```

There is a folder called `extensions` but no `commands.json`.

**Comment by pomdtr** [comment]
Yeah, it expects the latest version from master (which includes breaking changes). I'll ping you when it is available on brew.

**Comment by b-per** [comment]
Cool, I'll wait a bit then!

**Comment by pomdtr** [comment]
Hey, small ping to notify you that the extension is working again with the latest version of sunbeam :)
